version: "3.5"
services:
  database:
    image: mysql:8.1
    volumes:
      - ./data:/var/lib/mysql
      - ./setup_db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      MYSQL_ROOT_PASSWORD: "passw"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  nicebot:
    build: .
    depends_on:
      database:
        condition: service_healthy