services:
  database:
    image: mysql:8.1
    volumes:
      - ./data:/var/lib/mysql
#      - ./setup_db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command:
      - --skip-performance-schema
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.400'
          memory: 256M
  nicebot:
    image: ghcr.io/darkhenk13/betteruseroftheday:master
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
    depends_on:
      database:
        condition: service_healthy
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.250'
          memory: 250M