version: "3.5"
services:
  database:
    image: mysql:8.1
    volumes:
      - ./data:/var/lib/mysql
      - ./setup_db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      MYSQL_ROOT_PASSWORD: "passw"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  nicebot:
    build: ./nice_bot
    volumes:
      - ./nice_bot:/usr/src/app
    environment:
      BOT_TOKEN: "TOKEN"
      DB_USER: "bot"
      DB_PASSWORD: "11111"
      DB_NAME: "test_database"
      DB_HOST: "database"
    depends_on:
      database:
        condition: service_healthy