BILLY_TEAR_OFF_VEST = 'CAACAgIAAxkBAAEIcRNkKxD1kytU2onQeZaO_WDgSaUV2gACAhgAAnLcwEt56Ty4vsWYDC8E'
DRINK_CHAMPAGNE = 'CAACAgIAAxkBAAEIdW5kLF5B8ohszTGZmCfZc4bFGFs-jgACdhIAAszdyUv8JECqGA168S8E'

CUSTOM_STICKERS_PIDOR = ['CAACAgIAAxkBAAEFEF5mL14_hIRLJvUNDllNlXxo1JJd6gACdSQAAkz8sEnJJxELocvlpjQE',
                         'CAACAgIAAxkBAAEFEGJmL15peZFriXae49e_BbjBj-vlfQACQAADwTsUPgpTjCHlNO_ONAQ',
                         'CAACAgIAAxkBAAEFEGRmL16IgANacd4SN4Qa635O5X1nQAACUBkAAmJm2UvRfPms-O-SWTQE']
CUSTOM_STICKERS_HANDSOME = ['CAACAgIAAxkBAAEE_8hmK2E5Nr3E4iNoW9qVe_poiheIyAACXS4AAvYG2ElBs1tQ9kSO-TQE',
                            'CAACAgIAAxkBAAEFEA9mL0xFJy49P3KhNFFtZRcGqG8cqQACkTsAAuLIMEo3c6GY-Q88PDQE',
                            'CAACAgIAAxkBAAEFEFxmL14wwKnYD4yt81cirUsfksi0SAACDCEAAnNkKUkx1OYTxDVgvzQE']